#!/usr/bin/env ruby
# Toy Lang!
# 
# usage :
#   ./toylang example.toy   # to eval a file
#   ./toylang               # to start the REPL
#
# on Windows run with: ruby toylang [options]

$:.unshift "." # fix for Ruby 1.9

require "interpreter"
require "readline"

interpreter = Interpreter.new

# if a file is given we eval it
if file = ARGV.first
  interpreter.eval File.read(file)
  
