#!/usr/bin/env ruby
# Toy Lang!
# 
# usage :
#   ./toylang example.toy   # to eval a file
#   ./toylang               # to start the REPL
#
# on Windows run with: ruby toylang [options]

$:.unshift "." # fix for Ruby 1.9

require "interpreter"
require "readline"

interpreter = Interpreter.new

# if a file is given we eval it
if file = ARGV.first
  interpreter.eval File.read(file)
  
# start the REPL, read-eval-print-loop
else
  puts "ToyLang REPL - William Oliveira <sudowilliam@gmail.com>"
  puts "CTRL+C to quit"
  
  loop do
    line = Readline::readline(">> ")
    Readline::HISTORY.push(line)
    value = interpreter.eval(line)
    puts "=> #{value.ruby_value.inspect}"
  end
  
end